[package]
name = "michaeljoy"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hyper = {version = "0", features = ["full"]}
tokio = {version = "1", features = ["full"]}
futures = "0"
json = "0"
