[package]
name = "michaeljoy"
version = "0.1.0"
edition = "2021"

[profile.release]
strip = true     # automatically strip symbols from the binary
opt-level = "s"   # optimize for size
lto = true        # enable link time optimization
codegen-units = 1 # maximize size reduction optimizations
panic = "abort"   # abort instead of unwinding the code on panic

[dependencies]
tokio = {version = "1", features = ["fs", "macros", "rt-multi-thread", "signal"]}
warp = "0.3"
