[package]
name = "michaeljoy"
version = "0.1.0"
edition = "2021"

[profile.release]
debug = true
#strip = true     # automatically strip symbols from the binary
opt-level = "s"   # optimize for size
lto = true        # enable link time optimization
codegen-units = 1 # maximize size reduction optimizations
panic = "abort"   # abort instead of unwinding the code on panic

[dependencies]
chrono = "0.4.31"
hyper = {version = "0.14", features = ["full"]}
hyper-rustls = "0.24.2"
rustls = { version = "0.21.5", features = ["tls12"] }
rustls-pemfile = "1.0"
tokio = {version = "1", features = ["full"]}
